const homeActionTypes = {
	suggest: {
		GET_SUGGEST: "GET_SUGGEST",
		SET_LOADING_SUGGEST: "SET_LOADING_SUGGEST",
	},
	collection: {
		GET_COLLECTION: "GET_COLLECTION",
		SET_LOADING_COLLECTION: "SET_LOADING_COLLECTION",
	},
	chart: {
		GET_SONG_CHART: "GET_SONG_CHART",
		SET_LOADING_SONGCHART: "SET_LOADING_SONGCHART",

		GET_ARTIST_CHART: "GET_ARTIST_CHART",
		SET_LOADING_ARTISTCHART: "SET_LOADING_ARTISTCHART",
	},
	weekChart: {
		GET_WEEK_CHART: "GET_WEEK_CHART",
		SET_LOADING_WEEKCHART: "SET_LOADING_WEEKCHART",
	},
};

const detailActionTypes = {
	GET_SONG_DETAIL: "GET_SONG_DETAIL",
	SET_LOADING_SONG_DETAIL: "SET_LOADING_SONG_DETAIL",
	GET_SIMILAR_SONG: "GET_SIMILAR_SONG",
	SET_LOADING_SIMILAR: "SET_LOADING_SIMILAR",
	GET_COMMENTS: "GET_COMMENTS",
	SET_LOADING_COMMENTS: "SET_LOADING_COMMENTS",
	EMPTY_DETAIL: "EMPTY_DETAIL",
};

const favActionTypes = {
	ADD_FAV: "ADD_FAV",
	REMOVE_FAV: "REMOVE_FAV",
	GET_FAV: "GET_FAV",
	GET_FAV_STORAGE: "GET_FAV_STORAGE",
};

const searchActionTypes = {
	SEARCH_SONG: "SEARCH_SONG",
	SET_LOADING_SEARCH: "SET_LOADING_SEARCH",
	EMPTY_SEARCH: "EMPTY_SEARCH",
};

export {
	homeActionTypes,
	detailActionTypes,
	favActionTypes,
	searchActionTypes,
};
