export default {
	GET_MUSIC_LIST: "GET_MUSIC_LIST",
	GET_MUSIC_DETAIL: "GET_MUSIC_DETAIL",
	GET_SIMILAR_SONG: "GET_SIMILAR_SONG",
	GET_COMMENTS: "GET_COMMENTS",
	ADD_FAV: "ADD_FAV",
	REMOVE_FAV: "REMOVE_FAV",
};
