export const ActionType_Auth = {
	LOGIN: "LOGIN",
	LOGOUT: "LOGOUT",
	SIGNUP: "SIGNUP",
	SET_LOADING_LOGIN: "SET_LOADING_LOGIN",
	SET_LOADING_SIGNUP: "SET_LOADING_SIGNUP",
	SET_LOADING_STORAGE: "SET_LOADING_STORAGE",
};
