export const ActionType_Detail = {
	GET_TRACK_DETAIL: "GET_TRACK_DETAIL",
	SET_LOADING_TRACK_DETAIL: "SET_LOADING_TRACK_DETAIL",
	GET_SIMILAR_SONGS: "GET_SIMILAR_SONGS",
	SET_LOADING_SIMILAR: "SET_LOADING_SIMILAR",
	GET_COMMENTS: "GET_COMMENTS",
	SET_LOADING_COMMENTS: "SET_LOADING_COMMENTS",
	EMPTY_DETAIL: "EMPTY_DETAIL",
};
