export const ActionType_Home = {
	suggestList: {
		GET_SUGGESTLIST: "GET_SUGGESTLIST",
		SET_LOADING_SUGGESTLIST: "SET_LOADING_SUGGESTLIST",
	},
	collection: {
		GET_COLLECTION: "GET_COLLECTION",
		SET_LOADING_COLLECTION: "SET_LOADING_COLLECTION",
	},
	trackChart: {
		GET_TRACKCHART: "GET_TRACKCHART",
		SET_LOADING_TRACKCHART: "SET_LOADING_TRACKCHART",
	},
	artistChart: {
		GET_ARTISTCHART: "GET_ARTISTCHART",
		SET_LOADING_ARTISTCHART: "SET_LOADING_ARTISTCHART",
	},
	weekChart: {
		GET_WEEKCHART_TRACKS: "GET_WEEKCHART_TRACKS",
		GET_WEEKCHART_ALBUMS: "GET_WEEKCHART_ALBUMS",
		SET_LOADING_WEEKCHART_TRACKS: "SET_LOADING_WEEKCHART_TRACKS",
		SET_LOADING_WEEKCHART_ALBUMS: "SET_LOADING_WEEKCHART_ALBUMS",
	},
};
